title: AVAA
description:
baseurl:
url: http://www.avartifactatlas.com/
collections:
  artifacts:
    output: true
  formats:
    output: true

defaultlang: eng
t:
  English:
    title: 'A/V Artifact Atlas'
    description: ''
  Espa√±ol:
    title: 'A/V Artifact Atlas'
    description: ''
    home: es


prose:
  rooturl: '_artifacts'
  siteurl: 'http://www.avartifactatlas.com/'
  relativeLinks: 'http://www.avartifactatlas.com/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _artifacts:
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Video"
              value: "video"
            - name: "Analog"
              value: "analog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
