title: AVAA
description:
logo: # 120x120 px default
teaser: # 400x250 px default
locale:
baseurl: /avaa
url: http://bavc.github.io
collections: 
  artifacts:
    output: true
prose:
  rooturl: '_artifacts'
  siteurl: 'http://bavc.github.io/avaa/'
  relativeLinks: 'http://bavc.github.io/avaa/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _artifacts:
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Video"
              value: "video"
            - name: "Analog"
              value: "analog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          